export const availableCurrencies = [
  { name: "United States Dollar", tag: "usd" },
  { name: "Euro", tag: "eur" },
  { name: "British Pound Sterling", tag: "gbp" },
  { name: "Japanese Yen", tag: "jpy" },
  { name: "Australian Dollar", tag: "aud" },
  { name: "Canadian Dollar", tag: "cad" },
  { name: "Swiss Franc", tag: "chf" },
  { name: "Chinese Yuan", tag: "cny" },
  { name: "Swedish Krona", tag: "sek" },
  { name: "New Zealand Dollar", tag: "nzd" },
  { name: "South African Rand", tag: "zar" },
  { name: "Indian Rupee", tag: "inr" },
  { name: "Brazilian Real", tag: "brl" },
  { name: "Russian Ruble", tag: "rub" },
  { name: "Turkish Lira", tag: "try" },
  { name: "South Korean Won", tag: "krw" },
  { name: "Mexican Peso", tag: "mxn" },
  { name: "Indonesian Rupiah", tag: "idr" },
  { name: "Hong Kong Dollar", tag: "hkd" },
  { name: "Singapore Dollar", tag: "sgd" },
  { name: "Norwegian Krone", tag: "nok" },
  { name: "Malaysian Ringgit", tag: "myr" },
  { name: "Philippine Peso", tag: "php" },
  { name: "Thai Baht", tag: "thb" },
  { name: "Israeli New Shekel", tag: "ils" },
  { name: "Danish Krone", tag: "dkk" },
  { name: "Polish Złoty", tag: "pln" },
  { name: "Hungarian Forint", tag: "huf" },
  { name: "Czech Koruna", tag: "czk" },
  { name: "United Arab Emirates Dirham", tag: "aed" },
  { name: "Chilean Peso", tag: "clp" },
  { name: "Saudi Riyal", tag: "sar" },
  { name: "Romanian Leu", tag: "ron" },
  { name: "Nigerian Naira", tag: "ngn" },
  { name: "Kenyan Shilling", tag: "kes" },
  { name: "Egyptian Pound", tag: "egp" },
  { name: "Colombian Peso", tag: "cop" },
  { name: "Vietnamese Dong", tag: "vnd" },
  { name: "Iraqi Dinar", tag: "iqd" },
  { name: "Qatari Riyal", tag: "qar" },
  { name: "Argentine Peso", tag: "ars" },
  { name: "Peruvian Sol", tag: "pen" },
  { name: "Uruguayan Peso", tag: "uyu" },
  { name: "Bolivian Boliviano", tag: "bob" },
  { name: "Dominican Peso", tag: "dop" },
  { name: "Costa Rican Colón", tag: "crc" },
  { name: "Guatemalan Quetzal", tag: "gtq" },
  { name: "Honduran Lempira", tag: "hnl" },
  { name: "Nicaraguan Córdoba", tag: "nio" },
  { name: "Paraguayan Guarani", tag: "pyg" },
  { name: "Cuban Peso", tag: "cup" },
  { name: "Fijian Dollar", tag: "fjd" },
  { name: "Nepalese Rupee", tag: "npr" },
  { name: "Omani Rial", tag: "omr" },
  { name: "Panamanian Balboa", tag: "pab" },
  { name: "Pakistani Rupee", tag: "pkr" },
  { name: "Sri Lankan Rupee", tag: "lkr" },
  { name: "Tongan Pa'anga", tag: "top" },
  { name: "Tanzanian Shilling", tag: "tzs" },
  { name: "Ukrainian Hryvnia", tag: "uah" },
  { name: "Ugandan Shilling", tag: "ugx" },
  { name: "Israeli Old Shekel", tag: "ils" },
  { name: "Ghanaian Cedi", tag: "ghs" },
  { name: "Guernsey Pound", tag: "ggp" },
  { name: "Gibraltar Pound", tag: "gip" },
  { name: "Guinean Franc", tag: "gnf" },
  { name: "Guatemalan Quetzal", tag: "gtq" },
  { name: "Guyanaese Dollar", tag: "gyd" },
  { name: "Croatian Kuna", tag: "hrk" },
  { name: "Haitian Gourde", tag: "htg" },
  { name: "Icelandic Króna", tag: "isk" },
  { name: "Jamaican Dollar", tag: "jmd" },
  { name: "Jordanian Dinar", tag: "jod" },
  { name: "Kyrgyzstani Som", tag: "kgs" },
  { name: "Cambodian Riel", tag: "khr" },
  { name: "Comorian Franc", tag: "kmf" },
  { name: "North Korean Won", tag: "kpw" },
  { name: "Kuwaiti Dinar", tag: "kwd" },
  { name: "Cayman Islands Dollar", tag: "kyd" },
  { name: "Kazakhstani Tenge", tag: "kzt" },
  { name: "Laotian Kip", tag: "lak" },
  { name: "Lebanese Pound", tag: "lbp" },
  { name: "Sri Lankan Rupee", tag: "link" },
  { name: "Liberian Dollar", tag: "lrd" },
  { name: "Lesotho Loti", tag: "lsl" },
  { name: "Litecoin", tag: "ltc" },
  { name: "Lithuanian Litas", tag: "ltl" },
  { name: "Luxembourgish Franc", tag: "luf" },
  { name: "Luna", tag: "luna" },
  { name: "Latvian Lats", tag: "lvl" },
  { name: "Libyan Dinar", tag: "lyd" },
  { name: "Moroccan Dirham", tag: "mad" },
  { name: "Moldovan Leu", tag: "mdl" },
  { name: "Malagasy Ariary", tag: "mga" },
  { name: "Malagasy Franc", tag: "mgf" },
  { name: "Macedonian Denar", tag: "mkd" },
  { name: "Myanmar Kyat", tag: "mmk" },
  { name: "Mongolian Tugrik", tag: "mnt" },
  { name: "Macanese Pataca", tag: "mop" },
  { name: "Mauritanian Ouguiya", tag: "mro" },
  { name: "Mauritanian Ouguiya", tag: "mru" },
  { name: "Maltese Lira", tag: "mtl" },
  { name: "Mauritian Rupee", tag: "mur" },
  { name: "Maldivian Rufiyaa", tag: "mvr" },
  { name: "Malawian Kwacha", tag: "mwk" },
  { name: "Mexican Peso", tag: "mxn" },
  { name: "Mexican Investment Unit", tag: "mxv" },
  { name: "Mozambican Metical", tag: "mzm" },
  { name: "Mozambican New Metical", tag: "mzn" },
  { name: "Namibian Dollar", tag: "nad" },
  { name: "Nigerian Naira", tag: "ngn" },
  { name: "Nicaraguan Córdoba", tag: "nio" },
  { name: "Dutch Guilder", tag: "nlg" },
  { name: "Norwegian Krone", tag: "nok" },
  { name: "Nepalese Rupee", tag: "npr" },
  { name: "New Zealand Dollar", tag: "nzd" },
  { name: "Omani Rial", tag: "omr" },
  { name: "Panamanian Balboa", tag: "pab" },
  { name: "Peruvian Nuevo Sol", tag: "pen" },
  { name: "Papua New Guinean Kina", tag: "pgk" },
  { name: "Philippine Peso", tag: "php" },
  { name: "Pakistani Rupee", tag: "pkr" },
  { name: "Polish Złoty", tag: "pln" },
  { name: "Portuguese Escudo", tag: "pte" },
  { name: "Paraguayan Guarani", tag: "pyg" },
  { name: "Qatari Rial", tag: "qar" },
  { name: "Romanian Leu", tag: "ron" },
  { name: "Serbian Dinar", tag: "rsd" },
  { name: "Russian Ruble", tag: "rub" },
  { name: "Rwandan Franc", tag: "rwf" },
  { name: "Saudi Riyal", tag: "sar" },
  { name: "Solomon Islands Dollar", tag: "sbd" },
  { name: "Seychellois Rupee", tag: "scr" },
  { name: "Sudanese Dinar", tag: "sdd" },
  { name: "Sudanese Pound", tag: "sdg" },
  { name: "Swedish Krona", tag: "sek" },
  { name: "Singapore Dollar", tag: "sgd" },
  { name: "Saint Helena Pound", tag: "shp" },
  { name: "Slovenian Tolar", tag: "sit" },
  { name: "Slovak Koruna", tag: "skk" },
  { name: "Sierra Leonean Leone", tag: "sle" },
  { name: "Sierra Leonean Leone", tag: "sll" },
  { name: "Somali Shilling", tag: "sos" },
  { name: "Seborga Luigino", tag: "spl" },
  { name: "Surinamese Dollar", tag: "srd" },
  { name: "Surinamese Guilder", tag: "srg" },
  { name: "São Tomé & Príncipe Dobra", tag: "std" },
  { name: "São Tomé & Príncipe Dobra", tag: "stn" },
  { name: "Salvadoran Colón", tag: "svc" },
  { name: "Syrian Pound", tag: "syp" },
  { name: "Swazi Lilangeni", tag: "szl" },
  { name: "Thai Baht", tag: "thb" },
  { name: "Tajikistani Somoni", tag: "tjs" },
  { name: "Turkmenistani Manat", tag: "tmm" },
  { name: "Turkmenistani Manat", tag: "tmt" },
  { name: "Tunisian Dinar", tag: "tnd" },
  { name: "Tongan Pa'anga", tag: "top" },
  { name: "Turkish Lira", tag: "trl" },
  { name: "Turkish Lira", tag: "try" },
  { name: "Trinidad & Tobago Dollar", tag: "ttd" },
  { name: "Tuvaluan Dollar", tag: "tvd" },
  { name: "Taiwan Dollar", tag: "twd" },
  { name: "Tanzanian Shilling", tag: "tzs" },
  { name: "Ukrainian Hryvnia", tag: "uah" },
  { name: "Ugandan Shilling", tag: "ugx" },
  { name: "Uniswap", tag: "uni" },
  { name: "United States Dollar", tag: "usd" },
  { name: "Uruguayan Peso", tag: "uyu" },
  { name: "Uzbekistani Som", tag: "uzs" },
  { name: "Vatican Lira", tag: "val" },
  { name: "Venezuelan Bolívar", tag: "veb" },
  { name: "Venezuelan Bolívar", tag: "ved" },
  { name: "Venezuelan Bolívar", tag: "vef" },
  { name: "Venezuelan Bolívar Soberano", tag: "ves" },
  { name: "Vietnamese Dong", tag: "vnd" },
  { name: "Vanuatu Vatu", tag: "vuv" },
  { name: "Samoan Tala", tag: "wst" },
  { name: "Central African CFA Franc", tag: "xaf" },
  { name: "Silver Ounce", tag: "xag" },
  { name: "Gold Ounce", tag: "xau" },
  { name: "Bitcoin", tag: "btc" },
  { name: "East Caribbean Dollar", tag: "xcd" },
  { name: "Special Drawing Rights", tag: "xdr" },
  { name: "Stellar", tag: "xlm" },
  { name: "West African CFA Franc", tag: "xof" },
  { name: "Palladium Ounce", tag: "xpd" },
  { name: "CFP Franc", tag: "xpf" },
  { name: "Platinum Ounce", tag: "xpt" },
  { name: "Ripple", tag: "xrp" },
  { name: "Yemeni Rial", tag: "yer" },
  { name: "South African Rand", tag: "zar" },
  { name: "Zambian Kwacha", tag: "zmk" },
  { name: "Zambian Kwacha", tag: "zmw" },
  { name: "Zimbabwean Dollar", tag: "zwd" },
  { name: "Zimbabwean Dollar", tag: "zwl" },
  { name: "Cardano", tag: "ada" },
  { name: "United Arab Emirates Dirham", tag: "aed" },
  { name: "Afghan Afghani", tag: "afn" },
  { name: "Albanian Lek", tag: "all" },
  { name: "Armenian Dram", tag: "amd" },
  { name: "Netherlands Antillean Guilder", tag: "ang" },
  { name: "Angolan Kwanza", tag: "aoa" },
  { name: "Argentine Peso", tag: "ars" },
  { name: "Austrian Schilling", tag: "ats" },
  { name: "Australian Dollar", tag: "aud" },
  { name: "Aruban Florin", tag: "awg" },
  { name: "Azerbaijani Manat", tag: "azm" },
  { name: "Azerbaijani Manat", tag: "azn" },
  { name: "Bosnia-Herzegovina Convertible Mark", tag: "bam" },
  { name: "Barbadian Dollar", tag: "bbd" },
  { name: "Bitcoin Cash", tag: "bch" },
  { name: "Bangladeshi Taka", tag: "bdt" },
  { name: "Belgian Franc", tag: "bef" },
  { name: "Bulgarian Lev", tag: "bgn" },
  { name: "Bahraini Dinar", tag: "bhd" },
  { name: "Burundian Franc", tag: "bif" },
  { name: "Bermudian Dollar", tag: "bmd" },
  { name: "Brunei Dollar", tag: "bnd" },
  { name: "Bolivian Boliviano", tag: "bob" },
  { name: "Brazilian Real", tag: "brl" },
  { name: "Bahamian Dollar", tag: "bsd" },
  { name: "Bhutanese Ngultrum", tag: "btn" },
  { name: "Botswanan Pula", tag: "bwp" },
  { name: "Belarusian Ruble", tag: "byn" },
  { name: "Belarusian Ruble", tag: "byr" },
  { name: "Belize Dollar", tag: "bzd" },
  { name: "Canadian Dollar", tag: "cad" },
  { name: "Congolese Franc", tag: "cdf" },
  { name: "Swiss Franc", tag: "chf" },
  { name: "Chilean Unit of Account (UF)", tag: "clf" },
  { name: "Chilean Peso", tag: "clp" },
  { name: "Offshore Chinese Yuan", tag: "cnh" },
  { name: "Chinese Yuan", tag: "cny" },
  { name: "Colombian Peso", tag: "cop" },
  { name: "Costa Rican Colón", tag: "crc" },
  { name: "Cuban Convertible Peso", tag: "cuc" },
  { name: "Cuban Peso", tag: "cup" },
  { name: "Cape Verdean Escudo", tag: "cve" },
  { name: "Cypriot Pound", tag: "cyp" },
  { name: "Czech Koruna", tag: "czk" },
  { name: "German Mark", tag: "dem" },
  { name: "Djiboutian Franc", tag: "djf" },
  { name: "Danish Krone", tag: "dkk" },
  { name: "Dogecoin", tag: "doge" },
];
